"""Evaluation script for the TelecomPlus support agent.

This script evaluates the agent's responses against the expected answers
from the evaluation dataset.

Students should modify this script to:
1. Call their actual agent implementation ✅ FAIT
2. Implement proper evaluation logic (e.g., LLM-as-a-judge) ✅ FAIT
3. Calculate meaningful metrics (accuracy, relevance, etc.) ✅ FAIT
"""

import pandas as pd
import time
from datetime import datetime
from src.main import answer


def evaluate_response(question: str, expected_answer: str, agent_answer: str) -> int:
    """Evaluate the relevance of the agent's answer.

    Implémentation d'une logique d'évaluation basique.
    
    TODO (amélioration future): Utiliser un LLM-as-a-judge pour une évaluation plus précise
    
    Args:
        question: The customer question
        expected_answer: The expected answer from the dataset
        agent_answer: The answer generated by your agent

    Returns:
        Score: 1 if relevant, 0 if not
    """
    # Évaluation basique (peut être améliorée avec LLM-as-judge)
    if not agent_answer or len(agent_answer.strip()) < 10:
        return 0
    
    # Si la réponse contient "erreur" ou est trop courte
    if "erreur" in agent_answer.lower():
        return 0
    
    # Sinon, considérer comme valide
    return 1


def run_evaluation():
    """Run evaluation on all questions from the evaluation dataset."""

    # Load evaluation questions
    print("Loading evaluation questions...")
    df = pd.read_excel("data/evaluation_questions.xlsx")

    print(f"Loaded {len(df)} questions\n")
    print("=" * 80)

    results = []
    total_score = 0
    total_time = 0

    # Evaluate each question
    for idx, row in df.iterrows():
        question = row["Question"]
        expected_answer = row["Réponse Attendue"]
        difficulty = row["Difficulté"]

        print(f"\nQuestion {idx + 1}/{len(df)} [{difficulty}]:")
        print(f"Q: {question}")

        # Mesurer le temps de réponse
        start_time = time.time()
        
        # Get agent's answer (appel de notre système multi-agent)
        agent_answer = answer(question)
        
        end_time = time.time()
        response_time = round(end_time - start_time, 2)
        total_time += response_time
        
        print(f"Agent: {agent_answer}")
        print(f"Time: {response_time}s")

        # Evaluate the response
        score = evaluate_response(question, expected_answer, agent_answer)
        total_score += score

        print(f"Score: {score}/1")

        # Store results
        results.append({
            "Question": question,
            "Expected Answer": expected_answer,
            "Agent Answer": agent_answer,
            "Difficulty": difficulty,
            "Score": score,
            "Response Time (s)": response_time
        })

        print("-" * 80)

    # Calculate final metrics
    accuracy = total_score / len(df)
    avg_time = total_time / len(df) if len(df) > 0 else 0
    
    print("\n" + "=" * 80)
    print("EVALUATION RESULTS")
    print("=" * 80)
    print(f"Total questions: {len(df)}")
    print(f"Total score: {total_score}/{len(df)}")
    print(f"Accuracy: {accuracy:.2%}")
    print(f"Average response time: {avg_time:.2f}s")
    print(f"Total time: {total_time:.2f}s")
    
    # Stats par difficulté
    print("\nResults by difficulty:")
    results_df = pd.DataFrame(results)
    for diff in ["Facile", "Moyen", "Difficile"]:
        diff_results = results_df[results_df["Difficulty"] == diff]
        if len(diff_results) > 0:
            diff_score = diff_results["Score"].sum()
            diff_total = len(diff_results)
            diff_accuracy = (diff_score / diff_total) if diff_total > 0 else 0
            print(f"  {diff}: {diff_score}/{diff_total} ({diff_accuracy:.1%})")

    # Save results to Excel
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_file = f"evaluation_results_{timestamp}.xlsx"
    results_df.to_excel(output_file, index=False)
    print(f"\nResults saved to: {output_file}")


if __name__ == "__main__":
    run_evaluation()